/*
INSERT INTO CASHCARD(ID, AMOUNT, OWNER) VALUES (1, 123.45, 'fg');
INSERT INTO CASHCARD(ID, AMOUNT, OWNER) VALUES (2, 1.00, 'fg');
INSERT INTO CASHCARD(ID, AMOUNT, OWNER) VALUES (3, 150.00, 'fg');
*/